#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# generate-data.sh — rebuilds data.js for The Dad Museum.
#
# HOW IT WORKS:
#   • Each subfolder of images/quiz/ is one dad. The FOLDER NAME is the correct
#     quiz answer for the questions inside it.
#   • Inside a dad folder, questions are CROP + FULL pairs named by question
#     number:   q1-crop.png  +  q1-full.jpg
#     The CROP is shown as the clue; after answering it reveals the FULL photo.
#   • images/gallery/ holds every other photo — shown on the museum wall.
#
# TO UPDATE PHOTOS:
#   1. Put each dad's question images in images/quiz/<DadName>/ as
#      qN-crop.png and qN-full.jpg pairs (same N = same question).
#   2. Put all other photos in images/gallery/.
#   3. Run:  ./generate-data.sh
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail
cd "$(dirname "$0")"

QUIZ_DIR="images/quiz"
GALLERY_DIR="images/gallery"
OUT="data.js"

# find the file matching "qN-crop.*" or "qN-full.*" in a folder (any extension)
find_part(){ # $1=dir  $2=qnum  $3=crop|full
  find "$1" -maxdepth 1 -type f -iname "q$2-$3.*" -size +0c | sort | head -n1
}

{
  echo "// AUTO-GENERATED by generate-data.sh — do not edit by hand."
  echo "// Re-run ./generate-data.sh after adding, moving, or renaming photos."
  echo "window.MUSEUM_DATA = {"

  # ── dads: folder names under images/quiz/ (the four answer choices) ─────────
  printf "  dads: ["
  first=1
  for dir in "$QUIZ_DIR"/*/; do
    [ -d "$dir" ] || continue
    name=$(basename "$dir")
    if [ $first -eq 1 ]; then first=0; else printf ", "; fi
    printf '"%s"' "$name"
  done
  echo "],"

  # ── quiz: crop/full pairs, sorted by question number ───────────────────────
  echo "  quiz: ["
  # collect "num<TAB>dad" for every crop found, then sort numerically
  for dir in "$QUIZ_DIR"/*/; do
    [ -d "$dir" ] || continue
    name=$(basename "$dir")
    find "$dir" -maxdepth 1 -type f -iname 'q*-crop.*' -size +0c | while read -r c; do
      num=$(basename "$c" | sed -nE 's/^[qQ]([0-9]+)-.*/\1/p')
      printf '%s\t%s\n' "$num" "$name"
    done
  done | sort -n | while IFS=$'\t' read -r num dad; do
    crop=$(find_part "$QUIZ_DIR/$dad" "$num" crop)
    full=$(find_part "$QUIZ_DIR/$dad" "$num" full)
    [ -n "$crop" ] && [ -n "$full" ] || { echo "  // WARNING: q$num in $dad missing crop or full" >&2; continue; }
    printf '    { q: %s, crop: "%s", full: "%s", answer: "%s" },\n' "$num" "$crop" "$full" "$dad"
  done
  echo "  ],"

  # ── gallery: wall photos, de-duplicated by content (md5), with dimensions ───
  #    Also excludes any photo identical to a quiz full-reveal image.
  echo "  gallery: ["
  if [ -d "$GALLERY_DIR" ]; then
    QF=$(find "$QUIZ_DIR" -type f -iname '*-full.*' -size +0c -exec md5 -q {} \; | tr '\n' ' ')
    seen=" "
    find "$GALLERY_DIR" -maxdepth 1 -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.webp' \) -size +0c | sort | while read -r f; do
      h=$(md5 -q "$f")
      case " $QF " in *" $h "*) continue ;; esac   # skip duplicates of quiz reveals
      case "$seen"   in *" $h "*) continue ;; esac   # skip repeated images
      seen="$seen$h "
      # use mdls — it reports EXIF-ORIENTED dimensions (matches what the browser
      # renders), so the frame's aspect ratio is correct even for rotated photos
      read w ht < <(mdls -name kMDItemPixelWidth -name kMDItemPixelHeight "$f" \
        | awk -F'= ' '/PixelWidth/{a=$2}/PixelHeight/{b=$2}END{gsub(/[^0-9]/,"",a);gsub(/[^0-9]/,"",b);print a, b}')
      printf '    { src: "%s", w: %s, h: %s },\n' "$f" "${w:-1600}" "${ht:-1066}"
    done
  fi
  echo "  ]"
  echo "};"
} > "$OUT"

n_quiz=$(grep -c 'crop:' "$OUT" || true)
n_gal=$(grep -c 'src:' "$OUT" || true)
echo "Wrote $OUT — quiz questions: $n_quiz, gallery photos: $n_gal"
